// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Data;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241022160333_fixDatabaseRelationships")]
    partial class fixDatabaseRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("api.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectOption")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Title");

                    b.ToTable("answers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CorrectOption = 3,
                            Title = "What is a correct syntax to output 'Hello World' in C#?"
                        },
                        new
                        {
                            Id = 2,
                            CorrectOption = 4,
                            Title = "Which data type is used to create a variable that should store text?"
                        });
                });

            modelBuilder.Entity("api.Models.Option", b =>
                {
                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int>("OptionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AnswerId", "OptionNumber");

                    b.ToTable("options", (string)null);

                    b.HasData(
                        new
                        {
                            AnswerId = 1,
                            OptionNumber = 1,
                            Description = "print('Hello World')"
                        },
                        new
                        {
                            AnswerId = 1,
                            OptionNumber = 2,
                            Description = "cout < < 'Hello World'"
                        },
                        new
                        {
                            AnswerId = 1,
                            OptionNumber = 3,
                            Description = "System.out.printLn('Hello World')"
                        },
                        new
                        {
                            AnswerId = 1,
                            OptionNumber = 4,
                            Description = "Console.WriteLine('Hello World')"
                        },
                        new
                        {
                            AnswerId = 2,
                            OptionNumber = 1,
                            Description = "myString"
                        },
                        new
                        {
                            AnswerId = 2,
                            OptionNumber = 2,
                            Description = "Txt"
                        },
                        new
                        {
                            AnswerId = 2,
                            OptionNumber = 3,
                            Description = "str"
                        },
                        new
                        {
                            AnswerId = 2,
                            OptionNumber = 4,
                            Description = "string"
                        });
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("api.Models.UserResponse", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("UserId", "AnswerId");

                    b.HasIndex("AnswerId");

                    b.ToTable("responses", (string)null);
                });

            modelBuilder.Entity("api.Models.Option", b =>
                {
                    b.HasOne("api.Models.Answer", "Answer")
                        .WithMany("Options")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");
                });

            modelBuilder.Entity("api.Models.UserResponse", b =>
                {
                    b.HasOne("api.Models.Answer", "Answer")
                        .WithMany("Responses")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.Models.User", "User")
                        .WithMany("Responses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Answer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Models.Answer", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
